// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebShopInfrastructure.Models;

#nullable disable

namespace WebShopInfrastructure.Migrations
{
    [DbContext(typeof(DbWebShopContext))]
    [Migration("20260310170421_FixProductCategoryCascade")]
    partial class FixProductCategoryCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebShopDomain.Model.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Customerid")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("cart_pkey");

                    b.HasIndex("Customerid");

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("WebShopDomain.Model.Cartitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cartid")
                        .HasColumnType("integer")
                        .HasColumnName("cartid");

                    b.Property<int?>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("cartitem_pkey");

                    b.HasIndex("Cartid");

                    b.HasIndex("Productid");

                    b.ToTable("cartitem", (string)null);
                });

            modelBuilder.Entity("WebShopDomain.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoryinfo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("categoryinfo");

                    b.Property<string>("Categoryname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoryname");

                    b.HasKey("Id")
                        .HasName("category_pkey");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("WebShopDomain.Model.Changetype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("changetype_pkey");

                    b.ToTable("changetype", (string)null);
                });

            modelBuilder.Entity("WebShopDomain.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("adress");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("fullname");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("customer_pkey");

                    b.HasIndex(new[] { "Email" }, "customer_email_key")
                        .IsUnique();

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("WebShopDomain.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Customerid")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<DateTime?>("Orderdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("orderdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Orderstatusid")
                        .HasColumnType("integer")
                        .HasColumnName("orderstatusid");

                    b.Property<decimal?>("Totalamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalamount");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("Order_pkey");

                    b.HasIndex("Customerid");

                    b.HasIndex("Orderstatusid");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("WebShopDomain.Model.Orderhistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Changedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Changedtypeid")
                        .HasColumnType("integer")
                        .HasColumnName("changedtypeid");

                    b.Property<string>("Newvalue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("newvalue");

                    b.Property<string>("Oldvalue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("oldvalue");

                    b.Property<int?>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.HasKey("Id")
                        .HasName("orderhistory_pkey");

                    b.HasIndex("Changedtypeid");

                    b.HasIndex("Orderid");

                    b.ToTable("orderhistory", (string)null);
                });

            modelBuilder.Entity("WebShopDomain.Model.Orderitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int?>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Totalprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalprice");

                    b.Property<decimal>("Unitprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unitprice");

                    b.HasKey("Id")
                        .HasName("orderitem_pkey");

                    b.HasIndex("Orderid");

                    b.HasIndex("Productid");

                    b.ToTable("orderitem", (string)null);
                });

            modelBuilder.Entity("WebShopDomain.Model.Orderstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Statusname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statusname");

                    b.HasKey("Id")
                        .HasName("orderstatus_pkey");

                    b.ToTable("orderstatus", (string)null);
                });

            modelBuilder.Entity("WebShopDomain.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Availableqty")
                        .HasColumnType("integer")
                        .HasColumnName("availableqty");

                    b.Property<int?>("Categoryid")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("product_pkey");

                    b.HasIndex("Categoryid");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("WebShopDomain.Model.Cart", b =>
                {
                    b.HasOne("WebShopDomain.Model.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("Customerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("cart_customerid_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebShopDomain.Model.Cartitem", b =>
                {
                    b.HasOne("WebShopDomain.Model.Cart", "Cart")
                        .WithMany("Cartitems")
                        .HasForeignKey("Cartid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("cartitem_cartid_fkey");

                    b.HasOne("WebShopDomain.Model.Product", "Product")
                        .WithMany("Cartitems")
                        .HasForeignKey("Productid")
                        .HasConstraintName("cartitem_productid_fkey");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebShopDomain.Model.Order", b =>
                {
                    b.HasOne("WebShopDomain.Model.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("Customerid")
                        .HasConstraintName("Order_customerid_fkey");

                    b.HasOne("WebShopDomain.Model.Orderstatus", "Orderstatus")
                        .WithMany("Orders")
                        .HasForeignKey("Orderstatusid")
                        .HasConstraintName("Order_orderstatusid_fkey");

                    b.Navigation("Customer");

                    b.Navigation("Orderstatus");
                });

            modelBuilder.Entity("WebShopDomain.Model.Orderhistory", b =>
                {
                    b.HasOne("WebShopDomain.Model.Changetype", "Changedtype")
                        .WithMany("Orderhistories")
                        .HasForeignKey("Changedtypeid")
                        .HasConstraintName("orderhistory_changedtypeid_fkey");

                    b.HasOne("WebShopDomain.Model.Order", "Order")
                        .WithMany("Orderhistories")
                        .HasForeignKey("Orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("orderhistory_orderid_fkey");

                    b.Navigation("Changedtype");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebShopDomain.Model.Orderitem", b =>
                {
                    b.HasOne("WebShopDomain.Model.Order", "Order")
                        .WithMany("Orderitems")
                        .HasForeignKey("Orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("orderitem_orderid_fkey");

                    b.HasOne("WebShopDomain.Model.Product", "Product")
                        .WithMany("Orderitems")
                        .HasForeignKey("Productid")
                        .HasConstraintName("orderitem_productid_fkey");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebShopDomain.Model.Product", b =>
                {
                    b.HasOne("WebShopDomain.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("product_categoryid_fkey");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebShopDomain.Model.Cart", b =>
                {
                    b.Navigation("Cartitems");
                });

            modelBuilder.Entity("WebShopDomain.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebShopDomain.Model.Changetype", b =>
                {
                    b.Navigation("Orderhistories");
                });

            modelBuilder.Entity("WebShopDomain.Model.Customer", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebShopDomain.Model.Order", b =>
                {
                    b.Navigation("Orderhistories");

                    b.Navigation("Orderitems");
                });

            modelBuilder.Entity("WebShopDomain.Model.Orderstatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebShopDomain.Model.Product", b =>
                {
                    b.Navigation("Cartitems");

                    b.Navigation("Orderitems");
                });
#pragma warning restore 612, 618
        }
    }
}
